# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.host_name = "sfpractice6" 

  config.vm.share_folder "MyProject", "/mnt/MyProject", ".", :create => true
  config.vm.provision "file", source: "run.sh", destination: "run.sh"
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.provision :shell, :path => "run.sh"
  # SSH Server port forwarding
  config.vm.forward_port 22, 2222
  # Django HTTP Server port forwarding
  config.vm.forward_port 8000, 8000
end
